Added config for inverse unit formatting (s/it)
clitic/kdam pull request #6
Opened 2022-11-16 20:25 UTC by N9199

It's a simple config, it only changes bar behaviour when `self.rate()<1` and it takes unit scale in consideration if it's also enabled.

2022-11-17 03:28 UTC, clitic requested changes

2022-11-17 03:28 UTC, clitic commented on src/progress/bar.rs
> +        } else if self.rate() < 1. {
This feature is good but first refactor code a bit. `self.rate()` is called here and again inside the block. Create a variable to store temporary rate value.

2022-11-17 14:47 UTC, clitic approved these changes

2022-11-17 14:50 UTC, merged

2022-11-17 20:59 UTC, N9199 commented
I just got home and realized that the last commit I made which included an important fix to the condition of the `fmt_rate` function didn't get through on time. Could you revert the merge and then merge the last commit?

2022-11-18 04:37 UTC, clitic commented
I will fix that and I have also realized that `inverse_unit` field is not used in `fmt_rate` function. I will fix all stuff without reverting this merge.